const Map<String, List<String>> topicPacks = {
  'General': [
    'Pizza',
    'Football',
    'Airport',
    'Hospital',
    'School',
    'Beach',
    'Wedding',
    'Dentist',
    'Camping',
    'Museum',
    'Library',
    'Cinema',
    'Park',
    'Train Station',
    'Supermarket',
    'Gym',
    'Bakery',
    'Concert',
    'Zoo',
    'Mountain',
  ],
  'Family': [
    'Zoo',
    'Birthday Party',
    'Playground',
    'Christmas',
    'Supermarket',
    'Swimming Pool',
    'Toy Store',
    'School Bus',
    'Pet Shop',
    'Ice Cream Shop',
    'Circus',
    'Aquarium',
    'Magic Show',
    'Treehouse',
    'Amusement Park',
  ],
  'Adult 18+': [
    'Blind Date',
    'Hangover',
    'Poker Night',
    'Conspiracy Theory',
    'Traffic Jam at 3am',
    'Tax Audit',
    'Office Gossip',
    'First Date',
    'High School Reunion',
    'Jury Duty',
  ],
};
