// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANIyZz_RBSr3UkaiGOyHHdGOO2N3m12-I',
    appId: '1:906391927011:web:fa788c247e211067e26dd6',
    messagingSenderId: '906391927011',
    projectId: 'tuushars-who-lied',
    authDomain: 'tuushars-who-lied.firebaseapp.com',
    storageBucket: 'tuushars-who-lied.firebasestorage.app',
    measurementId: 'G-ZNPMMCL3MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUaVJLdQC10086kJY8LFlMcI6pxmrJlW0',
    appId: '1:906391927011:android:1e21f524ed8c0144e26dd6',
    messagingSenderId: '906391927011',
    projectId: 'tuushars-who-lied',
    storageBucket: 'tuushars-who-lied.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMzJ9U0k-IpbkmgcMk0WTwuCxyfHqCs4Y',
    appId: '1:906391927011:ios:9b108570dcebe46fe26dd6',
    messagingSenderId: '906391927011',
    projectId: 'tuushars-who-lied',
    storageBucket: 'tuushars-who-lied.firebasestorage.app',
    iosBundleId: 'com.example.whoLied',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMzJ9U0k-IpbkmgcMk0WTwuCxyfHqCs4Y',
    appId: '1:906391927011:ios:9b108570dcebe46fe26dd6',
    messagingSenderId: '906391927011',
    projectId: 'tuushars-who-lied',
    storageBucket: 'tuushars-who-lied.firebasestorage.app',
    iosBundleId: 'com.example.whoLied',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANIyZz_RBSr3UkaiGOyHHdGOO2N3m12-I',
    appId: '1:906391927011:web:601190638cfad3cbe26dd6',
    messagingSenderId: '906391927011',
    projectId: 'tuushars-who-lied',
    authDomain: 'tuushars-who-lied.firebaseapp.com',
    storageBucket: 'tuushars-who-lied.firebasestorage.app',
    measurementId: 'G-1DP99HN7SL',
  );
}
